//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechFix
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Application()
        {
            this.MasterInApplication = new HashSet<MasterInApplication>();
            this.ServicesInTheApplication = new HashSet<ServicesInTheApplication>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateOfCreation { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<int> PeriodOfExecution { get; set; }
        public string ProblemDescription { get; set; }
        public Nullable<int> IdApplicationStatus { get; set; }
        public Nullable<int> IdManager { get; set; }
        public Nullable<int> IdClient { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<int> IdPaymentMethod { get; set; }
    
        public virtual ApplicationStatus ApplicationStatus { get; set; }
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterInApplication> MasterInApplication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicesInTheApplication> ServicesInTheApplication { get; set; }
    }
}
