//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechFix
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterInApplication
    {
        public int Id { get; set; }
        public Nullable<int> IdMaster { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> IdApplication { get; set; }
        public string Comments { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
